### ISSUE TITLE
Idea: A GitHub Actions to pull translations from Transifex

### ISSUE THREAD

**Issue by rffontenelle** [rffontenelle/docspush-transifex#25]
Each team has its own solution to pull translations from Transifex. Setting up a solution can be an issue to new teams that prefer to translate rather than keep reinventing the wheel.

How about a GitHub Actions perform all necessary actions to pull translations?

Workflow idea:

```yaml
   permissions:
     contents: write 
   steps:
    - name: Checkout the repository
       uses: actions/checkout@3
    - name: Pull translations
      uses: THIS_ACTION@main
      with:
        tx_token: ${{ secrets.TX_TOKEN }}
        cpython_branch: 3.12
        commit_and_push: true
```

- python-docs-uk has an awesome script that uses transifex-python package to pull translations from Transifex. It is simple and clean.
- README would instruct on setting up the Transifex API token as repository secret
- `commit_and_push` argument in the above example is to avoid the need for posterior commit and push, but leaving false would allow customized commit and push tasks.
- Note how cpython and dependencies wouldn't have to be set up in the language's workflow.
- A Docker-based or JavaScript-based github action? I've read JavaScript-based is faster, but I don't know if all these operations can be done other than in Docker-based.
- This repository could document suggestion to new teams using this new action
